---

algernon_config:
  verbose: false
  listen:
    address: "{{ algernon_listen_address }}"
    port: "{{ algernon_listen_port }}"
  data_directory: "{{ algernon_data_directory }}"
  #  Sets a cache mode. The default is "on".
  #    "on"      - Cache everything.
  #    "dev"     - Everything, except Amber,
  #                Lua, GCSS, Markdown and JSX.
  #    "prod"    - Everything, except Amber and Lua.
  #    "small"   - Like "prod", but only files <= 64KB.
  #    "images"  - Only images (png, jpg, gif, svg).
  #    "off"     - Disable caching.
  cache: "on"
  # for redis support set HOST:PORT, e.g. 127.0.0.1:6379
  redis:
    host: 127.0.0.1
    port: 6379

...
