---

- name: create data directory
  file:
    path: "{{ algernon_data_directory }}"
    state: directory
    owner: "{{ algernon_system_user }}"
    group: "{{ algernon_system_group }}"
    mode: 0755

- name: create logfile
  file:
    path: "{{ algernon_config.access_log }}"
    state: touch
    owner: "{{ algernon_system_user }}"
    group: "{{ algernon_system_group }}"
    mode: 0666
  run_once: true
  when:
    - algernon_config.access_log is defined
    - algernon_config.access_log | length > 0

- name: create the systemd service file
  template:
    src: algernon.service.j2
    dest: "{{ systemd_lib_directory }}/algernon.service"
    owner: root
    group: root
    mode: 0644
  notify:
    - daemon-reload

- name: create the systemd service config file
  template:
    src: algernon.conf.j2
    dest: "{{ algernon_config_directory }}/algernon"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart algernon


...
