---

- name: resolve algernon release
  when:
    - not running_in_check_mode
  become: false
  delegate_to: localhost
  run_once: true
  bodsch.scm.scm_release:
    provider: "github"
    project: xyproto
    repository: algernon
    version: "{{ algernon_version }}" # "latest" | "2.53.0" | "v2.53.0"
    architecture: "{{ ansible_facts.architecture }}"
    system: "{{ ansible_facts.system }}"
    user: "{{ lookup('env', 'GH_USER') | default(omit) }}"
    password: "{{ lookup('env', 'GH_TOKEN') | default(omit) }}"
  register: _release

- name: re-define algernon_version
  when:
    - not running_in_check_mode
    - algernon_version == "latest"
    - _release.version is defined
    - _release.version | length > 0
  ansible.builtin.set_fact:
    algernon_version: "{{ _release.version }}"

- name: detect the downloaded algernon archive
  when:
    - not running_in_check_mode
  become: false
  delegate_to: "{{ algernon_delegate_to }}"
  run_once: "{{ 'false' if algernon_direct_download else 'true' }}"
  ansible.builtin.stat:
    path: "{{ algernon_local_tmp_directory }}/{{ _release.file }}"
  register: algernon_stat_archive

- name: define delegate instance for download handling
  when:
    - not running_in_check_mode
    - algernon_direct_download
  ansible.builtin.set_fact:
    algernon_delegate_to: "{{ ansible_facts.host }}"
    algernon_local_tmp_directory: "{{
      lookup('env', 'CUSTOM_LOCAL_TMP_DIRECTORY') |
      default('/var/cache/ansible/algernon', true) }}/{{ algernon_version }}"

- name: create download directory
  when:
    - not running_in_check_mode
  become: false
  delegate_to: "{{ algernon_delegate_to }}"
  run_once: "{{ 'false' if algernon_direct_download else 'true' }}"
  ansible.builtin.file:
    path: "{{ algernon_local_tmp_directory }}"
    state: directory
    mode: "0750"
  check_mode: false

- name: detect the downloaded algernon archive
  when:
    - not running_in_check_mode
  become: false
  delegate_to: "{{ algernon_delegate_to }}"
  run_once: "{{ 'false' if algernon_direct_download else 'true' }}"
  ansible.builtin.stat:
    path: "{{ algernon_local_tmp_directory }}/{{ _release.file }}"
  register: stat_algernon_archive

- name: download
  when:
    - not running_in_check_mode
    - algernon_stat_archive.stat is defined
    - not algernon_stat_archive.stat.exists | default('false')
  block:

    - name: download algernon binary archive
      become: false
      delegate_to: "{{ algernon_delegate_to }}"
      run_once: "{{ 'false' if algernon_direct_download else 'true' }}"
      ansible.builtin.get_url:
        url: "{{ _release.download_url }}"
        url_username: "{{ lookup('env', 'GH_USER') | default(omit) }}"
        url_password: "{{ lookup('env', 'GH_TOKEN') | default(omit) }}"
        dest: "{{ algernon_local_tmp_directory }}/{{ _release.file }}"
        checksum: "{{ _release.checksum_string | default(omit) }}"
        mode: "0640"
      register: _download_archive
      until: _download_archive is succeeded
      retries: 5
      delay: 2
      check_mode: false

  rescue:
    - name: delete download directory
      become: false
      delegate_to: "{{ algernon_delegate_to }}"
      run_once: "{{ 'false' if algernon_direct_download else 'true' }}"
      ansible.builtin.file:
        path: "{{ algernon_local_tmp_directory }}"
        state: absent

    - name: exit with fail
      ansible.builtin.fail:
        msg: A serious error occurred when downloading the archive.

- name: detect downloaded file
  become: false
  delegate_to: "{{ algernon_delegate_to }}"
  run_once: "{{ 'false' if algernon_direct_download else 'true' }}"
  ansible.builtin.stat:
    path: "{{ algernon_local_tmp_directory }}/{{ _release.file }}"
  register: algernon_stat_archive

- name: detect extracted binary
  become: false
  delegate_to: "{{ algernon_delegate_to }}"
  run_once: "{{ 'false' if algernon_direct_download else 'true' }}"
  ansible.builtin.stat:
    path: "{{ algernon_local_tmp_directory }}/algernon"
  register: algernon_stat_binary

- name: extract algernon archive
  when:
    - not running_in_check_mode
    - algernon_stat_archive.stat is defined
    - algernon_stat_archive.stat.exists | default('false') | bool
    - algernon_stat_archive.stat.mimetype in ["application/zip","application/gzip","application/x-xz"]
    - algernon_stat_binary.stat is defined
    - not algernon_stat_binary.stat.exists | default('false') | bool
  become: false
  delegate_to: "{{ algernon_delegate_to }}"
  run_once: "{{ 'false' if algernon_direct_download else 'true' }}"
  ansible.builtin.unarchive:
    src: "{{ algernon_local_tmp_directory }}/{{ _release.file }}"
    dest: "{{ algernon_local_tmp_directory }}/"
    # copy: false
    remote_src: "{{ 'true' if algernon_direct_download else 'false' }}"
    extra_opts:
      - --strip-components=1

...
