---

- name: user and group handling
  when:
    - not running_in_check_mode
    - algernon_system_user != "root"
  block:
    - name: create algernon group
      ansible.builtin.group:
        name: "{{ algernon_system_group }}"
        state: present
        system: true

    - name: create algernon user
      ansible.builtin.user:
        name: "{{ algernon_system_user }}"
        groups: "{{ algernon_system_group }}"
        append: true
        shell: /usr/sbin/nologin
        system: true
        createhome: false
        home: /nonexistent

- name: create install directory
  when:
    - not running_in_check_mode
  ansible.builtin.file:
    path: "{{ algernon_install_path }}"
    state: directory
    owner: "{{ algernon_system_user }}"
    group: "{{ algernon_system_group }}"
    mode: "0755"

- name: deploy and activate algernon version {{ algernon_version }}
  when:
    - not running_in_check_mode
  bodsch.core.deploy_and_activate:
    src_dir: "{{ algernon_local_tmp_directory }}"
    install_dir: "{{ algernon_install_path }}"
    link_dir: "/usr/bin"
    remote_src: "{{ ('true' if algernon_direct_download else 'false') | bool }}"
    owner: "{{ algernon_system_user }}"
    group: "{{ algernon_system_group }}"
    mode: "0755"
    items:
      - name: algernon
  notify:
    - restart algernon

- name: create data directory
  when:
    - not running_in_check_mode
  ansible.builtin.file:
    path: "{{ algernon_data_directory }}"
    state: directory
    owner: "{{ algernon_system_user }}"
    group: "{{ algernon_system_group }}"
    mode: "0755"

- name: logfile
  when:
    - not running_in_check_mode
    - algernon_config.access_log is defined
    - algernon_config.access_log | length > 0
  block:
    - name: detect logfile
      ansible.builtin.stat:
        path: "{{ algernon_config.access_log }}"
      register: _logfile_exists

    - name: create logfile
      when:
        - not _logfile_exists.stat.exists | default('false')
      ansible.builtin.file:
        path: "{{ algernon_config.access_log }}"
        state: touch
        owner: "{{ algernon_system_user }}"
        group: "{{ algernon_system_group }}"
        mode: "0666"
      run_once: true

- name: systemd
  when:
    - not running_in_check_mode
    - ansible_facts.service_mgr | lower == "systemd"
  block:
    - name: create algernon run configuration
      ansible.builtin.template:
        src: algernon.conf.j2
        dest: "{{ algernon_config_directory }}/algernon"
        owner: root
        group: root
        mode: "0644"

    - name: create systemd service unit
      ansible.builtin.template:
        src: init/systemd/algernon.service.j2
        dest: "{{ systemd_lib_directory }}/algernon.service"
        owner: root
        group: root
        mode: "0644"
      notify:
        - daemon-reload
        - restart algernon

- name: create custom fact file
  when:
    - not running_in_check_mode
  bodsch.core.facts:
    name: algernon
    facts:
      version: "{{ algernon_version }}"
...
