---

- name: prepare
  ansible.builtin.import_tasks: prepare.yaml
  become: true
  tags:
    - algernon_prepare

- name: download
  ansible.builtin.include_tasks: download.yaml
  when:
    - not stat_algernon_binary.stat.exists

- name: install
  ansible.builtin.import_tasks: install.yaml
  become: true
  tags:
    - algernon_install

- name: service
  ansible.builtin.import_tasks: service.yaml
  become: true
  tags:
    - algernon_service

...
