---

- import_tasks: install.yml
  become: true
  tags:
    - algernon_install

- import_tasks: configure.yml
  become: true
  tags:
    - algernon_configure

- name: Ensure algernon is enabled on boot
  become: true
  service:
    name: algernon
    enabled: true
    state: started
  tags:
    - algernon_run
