---

- import_tasks: prepare.yaml
  become: true
  tags:
    - algernon_prepare

- import_tasks: install.yaml
  become: true
  tags:
    - algernon_install

- import_tasks: configure.yaml
  become: true
  tags:
    - algernon_configure

- import_tasks: service.yaml
  become: true
  tags:
    - algernon_service

...
