---

- name: Gather variables for each operating system
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution_file_variety | lower }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
  tags:
    - algernon_install
    - algernon_configure
    - algernon_run

- import_tasks: preflight.yml
  tags:
    - algernon_install
    - algernon_configure
    - algernon_run

- import_tasks: install.yml
  become: true
  tags:
    - algernon_install

- import_tasks: configure.yml
  become: true
  tags:
    - algernon_configure

- name: Ensure algernon is enabled on boot
  become: true
  systemd:
    daemon_reload: true
    name: algernon
    enabled: true
    state: started
  tags:
    - algernon_run
