---

- name: include OS specific configuration ({{ ansible_facts.distribution }} ({{ ansible_facts.os_family }}) {{ ansible_facts.distribution_major_version }})
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      paths:
        - "vars"
      files:
        # eg. debian-10 / ubuntu-20.04 / centos-8 / oraclelinux-8
        - "{{ ansible_facts.distribution | lower }}-{{ ansible_facts.distribution_major_version }}.yaml"
        # eg. debian / ubuntu / centos / oraclelinux
        - "{{ ansible_facts.distribution | lower }}.yaml"
        # eg. redhat / debian
        - "{{ ansible_facts.os_family | lower }}.yaml"
        - default.yaml
      skip: true

- name: detect ansible check_mode
  bodsch.core.check_mode:
  register: _check_mode

- name: define running_in_check_mode
  ansible.builtin.set_fact:
    running_in_check_mode: '{{ _check_mode.check_mode }}'

- name: dependecies
  when:
    - not running_in_check_mode
    - algernon_requirements | default([]) | count > 0
  block:
    - name: install dependency
      ansible.builtin.package:
        name: "{{ algernon_requirements }}"
        state: present

    - name: update facts to get latest information
      ansible.builtin.setup:

...
