---

- name: include OS specific configuration ({{ ansible_distribution }} ({{ ansible_os_family }}) {{ ansible_distribution_major_version }})
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      paths:
        - "vars"
      files:
        # eg. debian-10 / ubuntu-20.04 / centos-8 / oraclelinux-8
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yaml"
        # eg. debian / ubuntu / centos / oraclelinux
        - "{{ ansible_distribution | lower }}.yaml"
        # eg. redhat / debian
        - "{{ ansible_os_family | lower }}.yaml"
        - default.yaml
      skip: true

- name: merge algernon configuration between defaults and custom
  set_fact:
    algernon_config: "{{ algernon_defaults_config |
      combine( algernon_config, recursive=True ) }}"

- name: detect installed algernon version
  stat:
    path: "{{ algernon_bin }}_{{ algernon_version }}"
  register: stat_algernon_binary

...
