---

- name: restart algernon if needed
  ansible.builtin.meta: flush_handlers

- name: ensure algernon is enabled on boot
  become: true
  ansible.builtin.service:
    name: algernon
    enabled: true
    state: started

...
