---
- name: prepare container
  hosts: all
  gather_facts: true

  pre_tasks:
    - name: install netstat
      package:
        name: [ net-tools, iproute2 ]
        state: present
      when:
        - ansible_os_family | lower == 'archlinux'

    - debug:
        msg:
          - "os family            : {{ ansible_os_family }}"
          - "distribution         : {{ ansible_distribution }}"
          - "distribution version : {{ ansible_distribution_major_version }}"
          - "ansible version      : {{ ansible_version.full }}"
          - "python version       : {{ ansible_python.version.major }}"

