#!/bin/bash

set -e

org=bodsch
repo=$(basename $(git rev-parse --show-toplevel))


GH_REPOSITORY="${repo}"
GH_USERNAME="${org:-bodsch}"
GH_KEEP_WORKFLOWS="${GH_KEEP_WORKFLOWS:-2}"

python hooks/gh-clean.py
