---

name: delete workflow runs


on:
  schedule:
    - cron: "10 4 * * 0"

jobs:
  steps:
    - name: Delete workflow runs
      uses: MajorScruffy/delete-old-workflow-runs@v0.2.0
      with:
        repository: MajorScruffy/delete-old-workflow-runs   # replace this with your own repository
        older-than-seconds: 345600                          # remove all workflow runs older than 4 day
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
