---

name: code linter

on:
  workflow_dispatch:
  push:
    branches:
      - 'feature/**'
      - 'fix/**'
      - '!doc/**'
    paths:
      - 'plugins/**'
      - '.config/pycodestyle.cfg'
  pull_request:
    branches:
      - 'feature/**'
      - 'fix/**'
      - '!doc/**'
    paths:
      - 'plugins/**'
      - '.config/pycodestyle.cfg'

jobs:
  pycodestyle:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python_version:
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v6.0.1
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: 🐍 set up python
        uses: actions/setup-python@v6.1.0
        with:
          python-version: "${{ matrix.python_version }}"

      - name: Install test dependencies.
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install pycodestyle

      - name: run pycodestyle
        run: |
          pycodestyle $PWD --config=.config/pycodestyle.cfg --verbose --statistics --count --exclude=test_*.py --exclude=hooks/*.py

  yamllint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: check out the codebase.
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: install yamllint
        run: |
          python3 -m pip install yamllint
          python3 -m pip install ansible-lint

      - name: run yamllint
        run: |
          yamllint .

...
